base: &base
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  username: facsite

production:
  <<: *base
  database: facsite_development
  #database: facsite_production


development:
  <<: *base
  database: facsite_development

test:
  <<: *base
  database: facsite_test
